-- 코드를 입력하세요
-- SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, TOTAL_SALES FROM 
-- SELECT B.BOOK_ID,A.SALES,B.CATEGORY, B.AUTHOR_ID,B.PRICE  FROM BOOK_SALES  A LEFT JOIN BOOK B ON A.BOOK_ID=B.BOOK_ID
SELECT C.AUTHOR_ID,D.AUTHOR_NAME,C.CATEGORY,SUM(C.PRICE*C.SALES) AS TOTAL_SALES FROM (SELECT B.BOOK_ID,A.SALES,B.CATEGORY, B.AUTHOR_ID,B.PRICE  FROM BOOK_SALES  A LEFT JOIN BOOK B ON A.BOOK_ID=B.BOOK_ID WHERE YEAR(A.SALES_DATE)='2022' AND MONTH(A.SALES_DATE)='1') C LEFT JOIN AUTHOR D ON C.AUTHOR_ID=D.AUTHOR_ID GROUP BY D.AUTHOR_NAME,C.CATEGORY ORDER BY C.AUTHOR_ID ASC, C.CATEGORY DESC;