-- 코드를 입력하세요
-- SELECT  PRICE_GROUP, PRICE_GROUP FROM

-- SELECT *, (PRICE DIV 10000)*10000 AS PRICE_GROUP FROM PRODUCT ;


SELECT A.PRICE_GROUP, COUNT(*) AS PRODUCTS FROM (SELECT *, (PRICE DIV 10000)*10000 AS PRICE_GROUP FROM PRODUCT) A GROUP BY A.PRICE_GROUP ORDER BY PRICE_GROUP ASC;