-- 코드를 입력하세요
SELECT A.USER_ID, A.PRODUCT_ID FROM (SELECT USER_ID,PRODUCT_ID, COUNT(*) AS NUM FROM ONLINE_SALE GROUP BY USER_ID,PRODUCT_ID) A WHERE A.NUM > 1 ORDER BY USER_ID ASC, PRODUCT_ID DESC;

-- SELECT * FROM ONLINE_SALE ORDER BY USER_ID ASC;